version: 2

models:
  - name: stg_route
    columns:
      - name: route_id
        tests:
          - unique
          - not_null

  - name: stg_stop
    columns:
      - name: stop_id
        tests:
          - unique
          - not_null

  - name: stg_calendar
    columns:
      - name: service_id
        tests:
          - unique
          - not_null

  - name: stg_scheduled_stop_event
    columns:
      - name: route_id
        tests:
          - not_null
      - name: stop_id
        tests:
          - not_null